import Papa from "papaparse";
import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { normalizePlayerName } from "@/lib/normalize";
import { SLEEPER_LEAGUE_ID } from "@/lib/config";

const PLAYERS_URL="https://github.com/nflverse/nflverse-data/releases/download/players/players.csv";
const FF_IDS_URL="https://raw.githubusercontent.com/dynastyprocess/data/master/files/db_playerids.csv";
const statsUrl=(year:number)=>`https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_${year}.csv`;
type CsvRow=Record<string,string|undefined>;
export interface FootballSyncResult { profilesMatched:number; profileRowsStored:number; gameRowsStored:number; years:number[]; advancedRows:number; source:"nflverse"; directIdMatches:number; fallbackNameMatches:number; }
function num(value:unknown){const n=Number(value);return Number.isFinite(n)?n:0;}
function optionalInt(value:unknown){const n=Number(value);return Number.isInteger(n)&&n>0?n:null;}
function grade(score:number){return score>=85?"A":score>=70?"B":score>=52?"C":score>=35?"D":"F";}
async function fetchCsv(url:string,optional=false):Promise<CsvRow[]>{try{const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(30000)});if(!response.ok){if(optional)return[];throw new Error(`football data request failed (${response.status})`)}const text=await response.text(),parsed=Papa.parse<CsvRow>(text,{header:true,skipEmptyLines:true});return parsed.data;}catch(error){if(optional)return[];throw error;}}
async function storeProfiles(rows:Array<Record<string,unknown>>){let stored=0;for(let i=0;i<rows.length;i+=250){const batch=rows.slice(i,i+250);stored+=await prisma.$executeRaw`INSERT INTO "PlayerFootballProfile" ("playerId","sleeperId","gsisId","displayName",position,"draftYear","draftRound","draftPick","draftTeam",college,"birthDate","sourceUpdatedAt","updatedAt") SELECT x."playerId",x."sleeperId",x."gsisId",x."displayName",x.position,x."draftYear",x."draftRound",x."draftPick",x."draftTeam",x.college,x."birthDate",x."sourceUpdatedAt",x."updatedAt" FROM jsonb_to_recordset(${JSON.stringify(batch)}::jsonb) AS x("playerId" text,"sleeperId" text,"gsisId" text,"displayName" text,position text,"draftYear" int,"draftRound" int,"draftPick" int,"draftTeam" text,college text,"birthDate" text,"sourceUpdatedAt" timestamp,"updatedAt" timestamp) ON CONFLICT ("playerId") DO UPDATE SET "sleeperId"=EXCLUDED."sleeperId","gsisId"=EXCLUDED."gsisId","displayName"=EXCLUDED."displayName",position=EXCLUDED.position,"draftYear"=EXCLUDED."draftYear","draftRound"=EXCLUDED."draftRound","draftPick"=EXCLUDED."draftPick","draftTeam"=EXCLUDED."draftTeam",college=EXCLUDED.college,"birthDate"=EXCLUDED."birthDate","sourceUpdatedAt"=EXCLUDED."sourceUpdatedAt","updatedAt"=EXCLUDED."updatedAt"`;}
 return stored;}
async function storeGames(rows:Array<Record<string,unknown>>){let stored=0;for(let i=0;i<rows.length;i+=200){const batch=rows.slice(i,i+200);stored+=await prisma.$executeRaw`INSERT INTO "PlayerGameStat" (id,"playerId","sleeperId","gsisId",season,week,"seasonType",team,opponent,"gameDate","fantasyHalfPpr",completions,attempts,"passingYards","passingTds",interceptions,carries,"rushingYards","rushingTds",targets,receptions,"receivingYards","receivingTds","fumblesLost",grade,"gradeScore","performanceSummary",source,"sourceUpdatedAt","refreshRunId","rawPayload","observedAt") SELECT x.id,x."playerId",x."sleeperId",x."gsisId",x.season,x.week,x."seasonType",x.team,x.opponent,x."gameDate",x."fantasyHalfPpr",x.completions,x.attempts,x."passingYards",x."passingTds",x.interceptions,x.carries,x."rushingYards",x."rushingTds",x.targets,x.receptions,x."receivingYards",x."receivingTds",x."fumblesLost",x.grade,x."gradeScore",x."performanceSummary",x.source,x."sourceUpdatedAt",x."refreshRunId",x."rawPayload",x."observedAt" FROM jsonb_to_recordset(${JSON.stringify(batch)}::jsonb) AS x(id text,"playerId" text,"sleeperId" text,"gsisId" text,season int,week int,"seasonType" text,team text,opponent text,"gameDate" timestamp,"fantasyHalfPpr" float8,completions float8,attempts float8,"passingYards" float8,"passingTds" float8,interceptions float8,carries float8,"rushingYards" float8,"rushingTds" float8,targets float8,receptions float8,"receivingYards" float8,"receivingTds" float8,"fumblesLost" float8,grade text,"gradeScore" float8,"performanceSummary" text,source text,"sourceUpdatedAt" timestamp,"refreshRunId" text,"rawPayload" jsonb,"observedAt" timestamp) ON CONFLICT ("playerId",season,week,"seasonType") DO UPDATE SET team=EXCLUDED.team,opponent=EXCLUDED.opponent,"fantasyHalfPpr"=EXCLUDED."fantasyHalfPpr",completions=EXCLUDED.completions,attempts=EXCLUDED.attempts,"passingYards"=EXCLUDED."passingYards","passingTds"=EXCLUDED."passingTds",interceptions=EXCLUDED.interceptions,carries=EXCLUDED.carries,"rushingYards"=EXCLUDED."rushingYards","rushingTds"=EXCLUDED."rushingTds",targets=EXCLUDED.targets,receptions=EXCLUDED.receptions,"receivingYards"=EXCLUDED."receivingYards","receivingTds"=EXCLUDED."receivingTds","fumblesLost"=EXCLUDED."fumblesLost",grade=EXCLUDED.grade,"gradeScore"=EXCLUDED."gradeScore","performanceSummary"=EXCLUDED."performanceSummary",source=EXCLUDED.source,"sourceUpdatedAt"=EXCLUDED."sourceUpdatedAt","refreshRunId"=EXCLUDED."refreshRunId","rawPayload"=EXCLUDED."rawPayload","observedAt"=EXCLUDED."observedAt"`;}
 return stored;}
export async function refreshFootballUsageData(refreshRunId:string):Promise<FootballSyncResult>{
 const players=await prisma.player.findMany({where:{ownershipIntervals:{some:{validTo:null,manager:{league:{sleeperId:SLEEPER_LEAGUE_ID}}}}},select:{id:true,sleeperId:true,fullName:true,normalizedName:true,position:true,nflTeam:true}});
 const existingProfiles=await prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS count FROM "PlayerFootballProfile" pf JOIN "Player" p ON p.id=pf."playerId" WHERE EXISTS (SELECT 1 FROM "OwnershipInterval" oi JOIN "Manager" m ON m.id=oi."managerId" JOIN "League" l ON l.id=m."leagueId" WHERE oi."playerId"=p.id AND oi."validTo" IS NULL AND l."sleeperId"=${SLEEPER_LEAGUE_ID})`;
 const [catalog,idRows]=await Promise.all([fetchCsv(PLAYERS_URL),fetchCsv(FF_IDS_URL,true)]);
 const byNamePos=new Map<string,CsvRow[]>(),catalogByGsis=new Map<string,CsvRow>();
 for(const row of catalog){const name=row.display_name??row.football_name??row.full_name??`${row.first_name??""} ${row.last_name??""}`.trim(),position=(row.position??"").toUpperCase(),gsis=String(row.gsis_id??row.gsis_it_id??"").trim();if(gsis)catalogByGsis.set(gsis,row);if(!name||!position)continue;const key=`${normalizePlayerName(name)}|${position}`,list=byNamePos.get(key)??[];list.push(row);byNamePos.set(key,list)}
 const gsisBySleeper=new Map<string,string>();for(const row of idRows){const sleeper=String(row.sleeper_id??"").trim(),gsis=String(row.gsis_id??"").trim();if(sleeper&&gsis)gsisBySleeper.set(sleeper,gsis)}
 const now=new Date().toISOString(),profiles:Array<Record<string,unknown>>=[],gsisToPlayer=new Map<string,(typeof players)[number]>();let directIdMatches=0,fallbackNameMatches=0;
 for(const player of players){const directGsis=gsisBySleeper.get(player.sleeperId),directRow=directGsis?catalogByGsis.get(directGsis)??null:null,candidates=byNamePos.get(`${player.normalizedName}|${player.position}`)??[];let row=directRow??(candidates.length===1?candidates[0]:candidates.find(c=>String(c.latest_team??c.team??"").toUpperCase()===String(player.nflTeam??"").toUpperCase())??null);if(!row)continue;if(directRow)directIdMatches++;else fallbackNameMatches++;const gsis=String(directGsis??row.gsis_id??row.gsis_it_id??"").trim();if(gsis)gsisToPlayer.set(gsis,player);profiles.push({playerId:player.id,sleeperId:player.sleeperId,gsisId:gsis||null,displayName:row.display_name??player.fullName,position:player.position,draftYear:optionalInt(row.draft_year),draftRound:optionalInt(row.draft_round),draftPick:optionalInt(row.draft_pick),draftTeam:row.draft_club??row.draft_team??null,college:row.college_name??row.college??null,birthDate:row.birth_date??null,sourceUpdatedAt:now,updatedAt:now});}
 const profileRowsStored=await storeProfiles(profiles),currentYear=new Date().getUTCFullYear(),needsInitial=Number(existingProfiles[0]?.count??0)<players.length*.82,years=needsInitial?Array.from({length:Math.max(1,currentYear-2022+1)},(_,i)=>2022+i):[currentYear-1,currentYear],gameRecords:Array<Record<string,unknown>>=[];let advancedRows=0;
 for(const year of years){const rows=await fetchCsv(statsUrl(year),true);for(const row of rows){if(String(row.season_type??"REG").toUpperCase()!=="REG")continue;const gsis=String(row.player_id??"").trim(),player=gsisToPlayer.get(gsis);if(!player)continue;const season=Number(row.season??year),week=Number(row.week);if(!Number.isFinite(season)||!Number.isFinite(week))continue;const receptions=num(row.receptions),fantasyStandard=Number(row.fantasy_points),half=Number.isFinite(fantasyStandard)?fantasyStandard+receptions*.5:num(row.fantasy_points_ppr)-receptions*.5,opportunities=num(row.attempts)+num(row.carries)+num(row.targets),score=Math.max(0,Math.min(100,half/24*100));if(row.target_share||row.air_yards_share||row.wopr)advancedRows++;gameRecords.push({id:randomUUID(),playerId:player.id,sleeperId:player.sleeperId,gsisId:gsis,season,week,seasonType:"REG",team:row.recent_team??row.team??null,opponent:row.opponent_team??row.opponent??null,gameDate:null,fantasyHalfPpr:Number.isFinite(half)?half:0,completions:num(row.completions),attempts:num(row.attempts),passingYards:num(row.passing_yards),passingTds:num(row.passing_tds),interceptions:num(row.interceptions),carries:num(row.carries),rushingYards:num(row.rushing_yards),rushingTds:num(row.rushing_tds),targets:num(row.targets),receptions,receivingYards:num(row.receiving_yards),receivingTds:num(row.receiving_tds),fumblesLost:num(row.rushing_fumbles_lost)+num(row.receiving_fumbles_lost)+num(row.sack_fumbles_lost),grade:grade(score),gradeScore:score,performanceSummary:`${half.toFixed(1)} half-PPR points · ${opportunities.toFixed(0)} recorded opportunities`,source:"NFLVERSE",sourceUpdatedAt:now,refreshRunId,rawPayload:row,observedAt:now});}}
 const gameRowsStored=await storeGames(gameRecords);return{profilesMatched:profiles.length,profileRowsStored,gameRowsStored,years,advancedRows,source:"nflverse",directIdMatches,fallbackNameMatches};
}
