import { prisma } from "@/lib/prisma";
import { SLEEPER_LEAGUE_ID } from "@/lib/config";
import { getAllCurrentRosterEntries,getAllManagers } from "@/lib/queries";
import { getLatestSlotMap } from "@/lib/teamMetrics";
import { getPredictivePlayerModels } from "@/lib/predictive";
import { getMatchups,getNflState } from "@/lib/sleeper";
import { publicTeamName } from "@/lib/publicIdentity";
import { projectOptimalWeeklyPoints } from "@/lib/lineupProjection";
import { runLeagueSimulation,type SimulationContext,type SimulationWeek } from "@/lib/simulationCore";

export interface LeagueSimulationRow { managerId:string; teamName:string; projectedWeeklyPoints:number; powerRank:number; expectedWins:number; expectedSeed:number; playoffProbability:number; championshipProbability:number; modelCapital:number; marketCapital:number; window:"CONTENDER"|"MIDDLE"|"REBUILDER"; }
export interface LeagueSimulationResult { rows:LeagueSimulationRow[]; context:SimulationContext; iterations:number; scheduleSource:"SLEEPER"|"FALLBACK"; completedWeeks:number; productionCoverage:number; }
function fallbackWeeks(ids:string[],count:number):SimulationWeek[]{if(ids.length<2)return[];const base=[...ids],dummy=base.length%2?"__BYE__":null;if(dummy)base.push(dummy);const rounds:SimulationWeek[]=[];let rotation=[...base];for(let r=0;r<base.length-1;r++){const pairs:Array<[string,string]>=[];for(let i=0;i<base.length/2;i++){const a=rotation[i],b=rotation[base.length-1-i];if(a!=="__BYE__"&&b!=="__BYE__")pairs.push([a,b]);}rounds.push({pairs});rotation=[rotation[0],rotation[rotation.length-1],...rotation.slice(1,-1)];}return Array.from({length:count},(_,i)=>rounds[i%rounds.length]);}
function pairsFromMatchups(rows:Awaited<ReturnType<typeof getMatchups>>,rosterToManager:Map<number,string>):Array<[string,string]>{const groups=new Map<number,number[]>();for(const row of rows){if(row.matchup_id===null)continue;const list=groups.get(row.matchup_id)??[];list.push(row.roster_id);groups.set(row.matchup_id,list)}const pairs:Array<[string,string]>=[];for(const ids of groups.values()){if(ids.length!==2)continue;const a=rosterToManager.get(ids[0]),b=rosterToManager.get(ids[1]);if(a&&b)pairs.push([a,b]);}return pairs;}
export async function simulateDynastyBoys(iterations=2500):Promise<LeagueSimulationResult>{const[managers,entries,slotMap,league,state]=await Promise.all([getAllManagers(),getAllCurrentRosterEntries(),getLatestSlotMap(),prisma.league.findFirst({where:{sleeperId:SLEEPER_LEAGUE_ID},select:{settings:true}}),getNflState().catch(()=>null)]),ids=entries.map(e=>e.playerId),predictions=await getPredictivePlayerModels(ids),byManager=new Map<string,typeof entries>();for(const entry of entries){const list=byManager.get(entry.managerId)??[];list.push(entry);byManager.set(entry.managerId,list)}let playoffWeekStart=15,playoffTeams=6;try{const settings=league?.settings?JSON.parse(league.settings):{},s=settings?.settings??{};playoffWeekStart=Number(s.playoff_week_start)||15;playoffTeams=Number(s.playoff_teams)||6}catch{}const regularWeeks=Math.max(1,playoffWeekStart-1),rosterToManager=new Map(managers.map(m=>[m.sleeperRosterId,m.id])),managerById=new Map(managers.map(m=>[m.id,m])),matchupWeeks=await Promise.all(Array.from({length:regularWeeks},(_,i)=>getMatchups(SLEEPER_LEAGUE_ID,i+1).catch(()=>[]))),allSleeperPairs=matchupWeeks.map(rows=>pairsFromMatchups(rows,rosterToManager)),hasSleeperSchedule=allSleeperPairs.filter(p=>p.length>0).length>=Math.min(3,regularWeeks),fallback=fallbackWeeks(managers.map(m=>m.id),regularWeeks),completedWeeks=state&&String(state.season_type).toLowerCase().startsWith("reg")?Math.max(0,Math.min(regularWeeks,state.week-1)):0,baseWins=new Map(managers.map(m=>[m.id,0])),basePoints=new Map(managers.map(m=>[m.id,0]));if(completedWeeks>0){for(let week=0;week<completedWeeks;week++){const rows=matchupWeeks[week],groups=new Map<number,typeof rows>();for(const row of rows){if(row.matchup_id===null)continue;const list=groups.get(row.matchup_id)??[];list.push(row);groups.set(row.matchup_id,list);const managerId=rosterToManager.get(row.roster_id);if(managerId)basePoints.set(managerId,(basePoints.get(managerId)??0)+(Number(row.points)||0));}for(const group of groups.values()){if(group.length!==2)continue;const[a,b]=group,ma=rosterToManager.get(a.roster_id),mb=rosterToManager.get(b.roster_id);if(!ma||!mb)continue;if(a.points>b.points)baseWins.set(ma,(baseWins.get(ma)??0)+1);else if(b.points>a.points)baseWins.set(mb,(baseWins.get(mb)??0)+1);}}}
  const teamInputs=managers.map(manager=>{const roster=byManager.get(manager.id)??[],assets=roster.map(entry=>{const prediction=predictions.get(entry.playerId);return{id:entry.playerId,position:entry.player.position,projectedPpg:prediction?.projectedWeeklyPoints??2,slot:slotMap.get(`${manager.id}:${entry.playerId}`)??"BENCH"}}),mean=projectOptimalWeeklyPoints(assets),modelCapital=roster.reduce((s,e)=>s+(predictions.get(e.playerId)?.modelValue??predictions.get(e.playerId)?.currentValue??0),0),marketCapital=roster.reduce((s,e)=>s+(predictions.get(e.playerId)?.currentValue??0),0),sd=Math.max(8,mean*.17);return{manager,mean,sd,modelCapital,marketCapital};}),schedule:SimulationWeek[]=Array.from({length:regularWeeks-completedWeeks},(_,offset)=>{const week=completedWeeks+offset,pairs=hasSleeperSchedule&&allSleeperPairs[week]?.length?allSleeperPairs[week]:fallback[week];return{pairs}}),context:SimulationContext={teams:teamInputs.map(t=>({id:t.manager.id,mean:t.mean,sd:t.sd,baseWins:baseWins.get(t.manager.id)??0,basePoints:basePoints.get(t.manager.id)??0})),weeks:schedule,playoffTeams,seed:20260817},outcomes=runLeagueSimulation(context,iterations),outcomeById=new Map(outcomes.map(o=>[o.teamId,o])),rankedStrength=[...teamInputs].sort((a,b)=>b.mean-a.mean),rows:LeagueSimulationRow[]=teamInputs.map(team=>{const outcome=outcomeById.get(team.manager.id)!,playoff=outcome.playoffProbability,window=playoff>=.62?"CONTENDER":playoff<=.28?"REBUILDER":"MIDDLE";return{managerId:team.manager.id,teamName:publicTeamName(managerById.get(team.manager.id)??team.manager),projectedWeeklyPoints:team.mean,powerRank:rankedStrength.findIndex(x=>x.manager.id===team.manager.id)+1,expectedWins:outcome.expectedWins,expectedSeed:outcome.expectedSeed,playoffProbability:outcome.playoffProbability,championshipProbability:outcome.championshipProbability,modelCapital:Math.round(team.modelCapital),marketCapital:Math.round(team.marketCapital),window};}).sort((a,b)=>b.championshipProbability-a.championshipProbability||b.projectedWeeklyPoints-a.projectedWeeklyPoints),productionCoverage:predictions.size?([...predictions.values()].filter(p=>p.games>=3).length/predictions.size):0;return{rows,context,iterations,scheduleSource:hasSleeperSchedule?"SLEEPER":"FALLBACK",completedWeeks,productionCoverage};}
