export interface SimulationTeamInput { id:string; mean:number; sd:number; baseWins:number; basePoints:number; }
export interface SimulationWeek { pairs:Array<[string,string]>; }
export interface SimulationContext { teams:SimulationTeamInput[]; weeks:SimulationWeek[]; playoffTeams:number; seed:number; }
export interface SimulationOutcome { teamId:string; expectedWins:number; expectedSeed:number; playoffProbability:number; championshipProbability:number; }
function hashSeed(value:number){let x=value>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return x>>>0;}
function rngFactory(seed:number){let a=hashSeed(seed)||1;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function normal(rng:()=>number){let u=0,v=0;while(u===0)u=rng();while(v===0)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function play(a:SimulationTeamInput,b:SimulationTeamInput,rng:()=>number){const as=Math.max(0,a.mean+normal(rng)*a.sd),bs=Math.max(0,b.mean+normal(rng)*b.sd);return{a:as,b:bs,winner:as===bs?(rng()<.5?a.id:b.id):as>bs?a.id:b.id};}
export function runLeagueSimulation(context:SimulationContext,iterations=2500,overrides?:Record<string,{mean?:number;sd?:number}>):SimulationOutcome[]{const teams=context.teams.map(team=>({...team,...(overrides?.[team.id]??{})})),byId=new Map(teams.map(t=>[t.id,t])),counts=new Map(teams.map(t=>[t.id,{wins:0,seeds:0,playoffs:0,titles:0}])),rng=rngFactory(context.seed);for(let iteration=0;iteration<iterations;iteration++){const record=new Map(teams.map(t=>[t.id,{wins:t.baseWins,points:t.basePoints}]));for(const week of context.weeks){for(const[p1,p2]of week.pairs){const a=byId.get(p1),b=byId.get(p2);if(!a||!b)continue;const r=play(a,b,rng),ra=record.get(a.id)!,rb=record.get(b.id)!;ra.points+=r.a;rb.points+=r.b;if(r.winner===a.id)ra.wins++;else rb.wins++;}}const ranked=[...teams].sort((a,b)=>{const ar=record.get(a.id)!,br=record.get(b.id)!;return br.wins-ar.wins||br.points-ar.points||b.mean-a.mean});ranked.forEach((team,index)=>{const c=counts.get(team.id)!;c.wins+=record.get(team.id)!.wins;c.seeds+=index+1;if(index<context.playoffTeams)c.playoffs++;});const field=ranked.slice(0,context.playoffTeams);let champion:string|null=null;if(field.length>=6){const qf1=play(field[2],field[5],rng),qf2=play(field[3],field[4],rng),q1=byId.get(qf1.winner)!,q2=byId.get(qf2.winner)!,remaining=[q1,q2].sort((a,b)=>ranked.findIndex(x=>x.id===a.id)-ranked.findIndex(x=>x.id===b.id)),semiLow=remaining[1],semiHigh=remaining[0],s1=play(field[0],semiLow,rng),s2=play(field[1],semiHigh,rng),final=play(byId.get(s1.winner)!,byId.get(s2.winner)!,rng);champion=final.winner;}else if(field.length>=2){let alive=[...field];while(alive.length>1){const next:SimulationTeamInput[]=[];for(let i=0;i<alive.length;i+=2){if(!alive[i+1]){next.push(alive[i]);continue;}next.push(byId.get(play(alive[i],alive[i+1],rng).winner)!);}alive=next;}champion=alive[0]?.id??null;}else champion=field[0]?.id??null;if(champion)counts.get(champion)!.titles++;}return teams.map(team=>{const c=counts.get(team.id)!;return{teamId:team.id,expectedWins:c.wins/iterations,expectedSeed:c.seeds/iterations,playoffProbability:c.playoffs/iterations,championshipProbability:c.titles/iterations};});}
