import { prisma } from "@/lib/prisma";
import { RosterSlot, Prisma } from "@/generated/prisma/client";
import { normalizePlayerName } from "@/lib/normalize";
import { getAllTransactions, getLeague, getNflState, getPlayerCatalog, getRosters, getUsers, type SleeperLeague, type SleeperNflState, type SleeperPlayer, type SleeperRoster, type SleeperTransaction, type SleeperUser } from "@/lib/sleeper";
import { PRIMARY_TEAM_NAME, SLEEPER_LEAGUE_ID } from "@/lib/config";

export interface SleeperSyncResult { leagueId:string; rosterChangesCount:number; playersRefreshed:number; mappingWarnings:{sleeperId:string;name:string;reason:string}[]; transactionsRecorded:number; }
type Tx=Prisma.TransactionClient;
interface FetchedSleeperData { sleeperLeague:SleeperLeague; users:SleeperUser[]; rosters:SleeperRoster[]; nflState:SleeperNflState; catalog:Record<string,SleeperPlayer>; completedTransactions:SleeperTransaction[]; }
function slotFor(roster:SleeperRoster,playerId:string):RosterSlot{if(roster.taxi?.includes(playerId))return RosterSlot.TAXI;if(roster.reserve?.includes(playerId))return RosterSlot.IR;if(roster.starters?.includes(playerId))return RosterSlot.STARTER;return RosterSlot.BENCH;}
async function fetchSleeperData():Promise<FetchedSleeperData>{const[sleeperLeague,users,rosters]=await Promise.all([getLeague(SLEEPER_LEAGUE_ID),getUsers(SLEEPER_LEAGUE_ID),getRosters(SLEEPER_LEAGUE_ID)]);const nflState=await getNflState().catch(()=>({week:1,season:sleeperLeague.season,season_type:"unknown"} as SleeperNflState));const throughWeek=Math.max(1,Math.min(nflState.week||1,18));const[catalog,transactions]=await Promise.all([getPlayerCatalog().catch(()=>({} as Record<string,SleeperPlayer>)),getAllTransactions(SLEEPER_LEAGUE_ID,throughWeek).catch(()=>[] as SleeperTransaction[])]);return{sleeperLeague,users,rosters,nflState,catalog,completedTransactions:transactions.filter((transaction)=>transaction.status==="complete")};}

async function persistSleeperData(db:Tx,data:FetchedSleeperData,refreshRunId:string):Promise<SleeperSyncResult>{
 const now=new Date();const{sleeperLeague,users,rosters,catalog,completedTransactions}=data;const rosterPositions=sleeperLeague.roster_positions??[];const formatParts=[rosterPositions.some((position)=>position==="SUPER_FLEX")?"Superflex":"1-QB",`${sleeperLeague.scoring_settings?.rec??0} PPR`];const league=await db.league.upsert({where:{sleeperId:sleeperLeague.league_id},update:{name:sleeperLeague.name,season:sleeperLeague.season,format:formatParts.join(", "),settings:JSON.stringify({roster_positions:sleeperLeague.roster_positions,scoring_settings:sleeperLeague.scoring_settings,settings:sleeperLeague.settings,status:sleeperLeague.status})},create:{sleeperId:sleeperLeague.league_id,name:sleeperLeague.name,season:sleeperLeague.season,format:formatParts.join(", "),settings:JSON.stringify({roster_positions:sleeperLeague.roster_positions,scoring_settings:sleeperLeague.scoring_settings,settings:sleeperLeague.settings,status:sleeperLeague.status})}});const usersById=new Map(users.map((user)=>[user.user_id,user]));await db.manager.updateMany({where:{leagueId:league.id},data:{isActive:false,isPrimaryTeam:false}});const managerByRosterId=new Map<number,{id:string}>();
 for(const roster of rosters){if(roster.owner_id==null)continue;const user=usersById.get(roster.owner_id);const displayName=user?.display_name??"Unknown Manager";const teamName=user?.metadata?.team_name??null;const isPrimaryTeam=teamName?.trim().toLowerCase()===PRIMARY_TEAM_NAME.toLowerCase();const manager=await db.manager.upsert({where:{leagueId_sleeperRosterId:{leagueId:league.id,sleeperRosterId:roster.roster_id}},update:{sleeperUserId:roster.owner_id,displayName,teamName,isPrimaryTeam,isActive:true},create:{leagueId:league.id,sleeperUserId:roster.owner_id,sleeperRosterId:roster.roster_id,displayName,teamName,isPrimaryTeam}});managerByRosterId.set(roster.roster_id,manager);}
 const rosteredPlayerIds=new Set<string>();for(const roster of rosters)for(const pid of roster.players??[])rosteredPlayerIds.add(pid);const existingPlayers=rosteredPlayerIds.size?await db.player.findMany({where:{sleeperId:{in:[...rosteredPlayerIds]}}}):[];const existingBySleeperId=new Map(existingPlayers.map((player)=>[player.sleeperId,player]));const mappingWarnings:SleeperSyncResult["mappingWarnings"]=[];const playerInternalId=new Map<string,string>();
 for(const sleeperId of rosteredPlayerIds){const meta=catalog[sleeperId];const existing=existingBySleeperId.get(sleeperId);const fullName=meta?.full_name??([meta?.first_name,meta?.last_name].filter(Boolean).join(" ")||existing?.fullName||sleeperId);const position=meta?.position??existing?.position??"UNK";const nflTeam=meta?(meta.team??null):(existing?.nflTeam??null);const status=meta?(meta.injury_status??meta.status??null):(existing?.status??null);const player=await db.player.upsert({where:{sleeperId},update:{fullName,normalizedName:normalizePlayerName(fullName),position,nflTeam,status},create:{sleeperId,fullName,normalizedName:normalizePlayerName(fullName),position,nflTeam,status,mappingStatus:"NEEDS_REVIEW"}});playerInternalId.set(sleeperId,player.id);if(!player.ktcId&&player.mappingStatus!=="MAPPED")mappingWarnings.push({sleeperId,name:fullName,reason:meta?"No KTC mapping yet — the market refresh will attempt to resolve it.":"No KTC mapping and Sleeper player metadata was unavailable on this run."});}
 const snapshotRows:{refreshRunId:string;managerId:string;playerId:string;slot:RosterSlot;observedAt:Date}[]=[];for(const roster of rosters){const manager=managerByRosterId.get(roster.roster_id);if(!manager)continue;for(const pid of roster.players??[]){const playerId=playerInternalId.get(pid);if(playerId)snapshotRows.push({refreshRunId,managerId:manager.id,playerId,slot:slotFor(roster,pid),observedAt:now});}}if(snapshotRows.length)await db.rosterSnapshot.createMany({data:snapshotRows});
 const transactionRows=completedTransactions.map((transaction)=>({leagueId:league.id,sleeperTransactionId:transaction.transaction_id,type:transaction.type,status:transaction.status,sleeperCreatedAt:new Date(transaction.created),rosterIdsInvolved:JSON.stringify(transaction.roster_ids??[]),adds:transaction.adds?JSON.stringify(transaction.adds):null,drops:transaction.drops?JSON.stringify(transaction.drops):null,draftPicks:transaction.draft_picks?JSON.stringify(transaction.draft_picks):null,waiverBudget:transaction.waiver_budget?JSON.stringify(transaction.waiver_budget):null,rawPayload:JSON.stringify(transaction)}));const transactionCreateResult=transactionRows.length?await db.transaction.createMany({data:transactionRows,skipDuplicates:true}):{count:0};const latestAddTimestamp=new Map<string,number>();const latestDropTimestamp=new Map<string,number>();for(const transaction of completedTransactions){for(const pid of Object.keys(transaction.adds??{}))latestAddTimestamp.set(pid,Math.max(latestAddTimestamp.get(pid)??0,transaction.created));for(const pid of Object.keys(transaction.drops??{}))latestDropTimestamp.set(pid,Math.max(latestDropTimestamp.get(pid)??0,transaction.created));}
 let rosterChangesCount=0;const currentOwnerBySleeperPid=new Map<string,number>();for(const roster of rosters)for(const pid of roster.players??[])currentOwnerBySleeperPid.set(pid,roster.roster_id);const openIntervals=await db.ownershipInterval.findMany({where:{manager:{leagueId:league.id},validTo:null},include:{player:{select:{sleeperId:true}}}});const openIntervalBySleeperPid=new Map(openIntervals.map((interval)=>[interval.player.sleeperId,interval]));for(const[sleeperPid,openInterval]of openIntervalBySleeperPid.entries()){const currentRosterId=currentOwnerBySleeperPid.get(sleeperPid);const currentManager=currentRosterId!=null?managerByRosterId.get(currentRosterId):undefined;if(currentManager?.id===openInterval.managerId)continue;const eventTs=Math.max(latestAddTimestamp.get(sleeperPid)??0,latestDropTimestamp.get(sleeperPid)??0);await db.ownershipInterval.update({where:{id:openInterval.id},data:{validTo:eventTs>0?new Date(eventTs):now}});rosterChangesCount++;}
 for(const[sleeperPid,playerId]of playerInternalId.entries()){const currentRosterId=currentOwnerBySleeperPid.get(sleeperPid);const currentManager=currentRosterId!=null?managerByRosterId.get(currentRosterId):undefined;if(!currentManager)continue;const priorOpen=openIntervalBySleeperPid.get(sleeperPid);if(priorOpen?.managerId===currentManager.id)continue;const addTs=latestAddTimestamp.get(sleeperPid)??0;await db.ownershipInterval.create({data:{playerId,managerId:currentManager.id,validFrom:addTs>0?new Date(addTs):now,validTo:null}});if(!priorOpen)rosterChangesCount++;}
 return{leagueId:league.id,rosterChangesCount,playersRefreshed:rosteredPlayerIds.size,mappingWarnings,transactionsRecorded:transactionCreateResult.count};
}
export async function syncSleeperState(refreshRunId:string):Promise<SleeperSyncResult>{const data=await fetchSleeperData();return prisma.$transaction((tx)=>persistSleeperData(tx,data,refreshRunId),{timeout:180_000});}
