import WaiverMarketBoard from "@/components/WaiverMarketBoard";
import SectionHeader from "@/components/SectionHeader";
import { getWaiverMarket } from "@/lib/waiverMarket";

export const dynamic="force-dynamic";

export default async function WaiversPage(){
  const data=await getWaiverMarket();
  const universeIncomplete=data.valuedUniverse<400;
  return <div className="min-w-0 space-y-5"><div><h1 className="text-xl font-semibold text-neutral-100">Waiver Market</h1><p className="mt-1 max-w-3xl text-sm leading-5 text-neutral-500">Fresh KTC-valued players who are not currently owned by any Dynasty Boys roster. Ownership comes from Sleeper; unknown players are never assumed to be free agents.</p></div>{universeIncomplete?<div className="rounded-lg border border-amber-900/70 bg-amber-950/20 p-3 text-[11px] leading-5 text-amber-200">The full KTC universe has not completed its first production refresh yet. This page currently knows {data.valuedUniverse} fresh valued players; the next scheduled market refresh will expand it to the full matched KTC/Sleeper universe rather than pretending missing players are waivers.</div>:null}<section className="rounded-lg border border-neutral-800 bg-neutral-900 p-3 sm:p-4"><SectionHeader title="Market coverage" description="A free-agent row appears only when both current KTC identity and current Sleeper non-ownership can be verified."/><div className="grid grid-cols-3 gap-2"><div className="rounded-md bg-neutral-950 p-2.5"><div className="text-[9px] uppercase tracking-wide text-neutral-600">Fresh valued universe</div><div className="mt-1 text-lg font-semibold text-neutral-100">{data.valuedUniverse}</div></div><div className="rounded-md bg-neutral-950 p-2.5"><div className="text-[9px] uppercase tracking-wide text-neutral-600">League-owned valued</div><div className="mt-1 text-lg font-semibold text-neutral-100">{data.ownedValued}</div></div><div className="rounded-md bg-neutral-950 p-2.5"><div className="text-[9px] uppercase tracking-wide text-neutral-600">Verified unrostered</div><div className="mt-1 text-lg font-semibold text-emerald-300">{data.rows.length}</div></div></div></section><section><SectionHeader title="Available players" description="Sort by current KTC or legitimate stored movement windows. No fabricated 7d/30d change is shown when a comparison point does not exist."/><WaiverMarketBoard rows={data.rows}/></section></div>;
}
