import Link from "next/link";
import { getAllCurrentRosterEntries } from "@/lib/queries";
import { computeMarketDataForPlayers } from "@/lib/metrics";
import { computeAllTeamValuations } from "@/lib/teamMetrics";
import RiserFallerTabs, { type MoverRow } from "@/components/RiserFallerTabs";
import SectionHeader from "@/components/SectionHeader";
import { formatPercent, formatPoints, formatSigned, trendColorClass, timeAgo } from "@/lib/format";

export const dynamic = "force-dynamic";
const DAY_MS = 86400000;
const TEAM_CHANGE_COVERAGE_MIN = 0.75;
function hasMeaningfulRange(sparkline: { value: number; observedAt: string }[]) { if (sparkline.length < 3) return false; return new Date(sparkline[sparkline.length - 1].observedAt).getTime() - new Date(sparkline[0].observedAt).getTime() >= 14 * DAY_MS; }
function comparableChange(value: number | null, coverage: number, total: number) { return value !== null && total > 0 && coverage / total >= TEAM_CHANGE_COVERAGE_MIN ? value : null; }

export default async function LeaguePage() {
  const entries = await getAllCurrentRosterEntries();
  const playerIds = entries.map((entry) => entry.playerId);
  const [marketData, valuations] = await Promise.all([computeMarketDataForPlayers(playerIds), computeAllTeamValuations()]);
  const moverRows: MoverRow[] = entries.map((entry) => { const market = marketData.get(entry.playerId)!; return { id: entry.player.id, fullName: entry.player.fullName, position: entry.player.position, teamName: entry.manager.teamName ?? entry.manager.displayName, currentValue: market.isStale ? null : market.currentValue, changeSinceLastRefresh: market.isStale ? null : market.changeSinceLastRefresh?.points ?? null, change7dPoints: market.isStale ? null : market.change7d?.points ?? null, change30dPoints: market.isStale ? null : market.change30d?.points ?? null }; }).filter((row) => row.currentValue !== null);
  const rankedTotal = [...valuations].sort((a, b) => b.totalDynastyValue - a.totalDynastyValue), rankedPlayers = [...valuations].sort((a, b) => b.playerCapital - a.playerCapital), rankedPicks = [...valuations].sort((a, b) => b.draftCapital - a.draftCapital), rankedLineup = [...valuations].sort((a, b) => b.optimalLineupValue - a.optimalLineupValue), rankedDepth = [...valuations].sort((a, b) => b.depthValue - a.depthValue);
  const ranks = (list: typeof valuations) => new Map(list.map((value, index) => [value.managerId, index + 1]));
  const totalRank = ranks(rankedTotal), playerRank = ranks(rankedPlayers), pickRank = ranks(rankedPicks), lineupRank = ranks(rankedLineup), depthRank = ranks(rankedDepth);
  const rangeEligible = entries.map((entry) => ({ entry, market: marketData.get(entry.playerId)! })).filter(({ market }) => !market.isStale && market.distanceFromHigh !== null && hasMeaningfulRange(market.sparkline));
  const nearHigh = [...rangeEligible].sort((a, b) => (b.market.distanceFromHigh?.percent ?? -999) - (a.market.distanceFromHigh?.percent ?? -999)).slice(0, 8);
  const drawdowns = [...rangeEligible].filter(({ market }) => (market.distanceFromHigh?.percent ?? 0) < 0).sort((a, b) => (a.market.distanceFromHigh?.percent ?? 0) - (b.market.distanceFromHigh?.percent ?? 0)).slice(0, 8);
  const staleTeams = valuations.filter((value) => value.stalePlayerCount > 0).length;
  const draftMarketAvailable = valuations.length > 0 && valuations.every((value) => value.draftMarketAvailable);
  const draftMarketStale = draftMarketAvailable && valuations.some((value) => value.draftMarketStale);
  const draftMarketObservedAt = valuations.find((value) => value.draftMarketObservedAt)?.draftMarketObservedAt ?? null;
  const capitalOrder = draftMarketAvailable ? rankedTotal : rankedPlayers;
  const capitalRank = draftMarketAvailable ? totalRank : playerRank;

  return <div className="min-w-0 space-y-7">
    <div><h1 className="text-xl font-semibold text-neutral-100">League Market</h1><p className="mt-1 max-w-3xl text-sm leading-5 text-neutral-500">Compare player capital, draft capital, optimized lineup strength and depth. Open any team for a full roster and position-by-position breakdown.</p></div>
    {staleTeams > 0 ? <div className="rounded-lg border border-amber-900/70 bg-amber-950/20 p-3 text-[11px] leading-5 text-amber-200">{staleTeams} team{staleTeams === 1 ? "" : "s"} currently include at least one stale KTC value. Capital rankings preserve each player’s latest validated value instead of converting stale assets to zero. Movement and player-level decisions still require fresh data.</div> : null}
    {draftMarketStale ? <div className="rounded-lg border border-amber-900/70 bg-amber-950/20 p-3 text-[11px] leading-5 text-amber-200">Draft capital is using the last verified pick board from {timeAgo(draftMarketObservedAt)} for ranking continuity. That stale board is excluded from current trade math.</div> : null}
    {!draftMarketAvailable ? <div className="rounded-lg border border-red-900/70 bg-red-950/20 p-3 text-[11px] leading-5 text-red-200">No verified live or stored draft-pick market is available. Draft rankings are withheld and the lead capital ranking below is explicitly player-only until a verified pick board returns.</div> : null}
    <section><SectionHeader title="League movers" description="Player movement only; fresh KTC values and legitimate comparison windows."/><RiserFallerTabs rows={moverRows}/></section>
    <section><SectionHeader title={draftMarketAvailable ? "Dynasty capital ranking" : "Player capital ranking"} description={draftMarketAvailable ? "Total capital = latest verified player capital + currently owned valued draft picks. Team movement appears only with at least 75% fresh comparison coverage." : "Draft capital is unavailable, so this fallback ranks only known player capital rather than presenting an incomplete total as complete."}/>
      <div className="space-y-2 md:hidden">{capitalOrder.map((value) => { const seven = comparableChange(value.change7d, value.change7dCoverage, value.playerCount); const capitalValue = draftMarketAvailable ? value.totalDynastyValue : value.playerCapital; return <Link href={`/league/${value.managerId}`} key={value.managerId} className="block rounded-lg border border-neutral-800 bg-neutral-900 p-3 transition hover:border-neutral-700 hover:bg-neutral-800/40"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-neutral-100">#{capitalRank.get(value.managerId)} · {value.teamName}</div><div className="mt-0.5 text-[10px] text-neutral-600">{value.valuedPlayerCount}/{value.playerCount} fresh{draftMarketAvailable ? ` · ${value.draftPickCount} valued picks` : " · picks withheld"}{value.stalePlayerCount ? ` · ${value.stalePlayerCount} stale` : ""}</div></div><div className="shrink-0 text-right"><div className={`text-lg font-semibold tabular-nums ${value.stalePlayerCount || draftMarketStale ? "text-amber-200" : "text-neutral-100"}`}>{formatPoints(capitalValue)}</div><div className="text-[9px] uppercase text-neutral-600">{draftMarketAvailable ? "total capital" : "player capital"}</div></div></div><div className="mt-3 grid grid-cols-5 gap-1.5 text-center">{[["Players", playerRank.get(value.managerId)], ["Picks", draftMarketAvailable ? pickRank.get(value.managerId) : "—"], ["Lineup", lineupRank.get(value.managerId)], ["Depth", depthRank.get(value.managerId)]].map(([label, rank]) => <div key={String(label)} className="rounded-md bg-neutral-950 p-2"><div className="text-[9px] text-neutral-600">{label}</div><div className="mt-0.5 text-xs font-semibold text-neutral-200">{typeof rank === "number" ? `#${rank}` : rank}</div></div>)}<div className="rounded-md bg-neutral-950 p-2"><div className="text-[9px] text-neutral-600">7d</div><div className={`mt-0.5 text-xs font-semibold ${trendColorClass(seven)}`}>{formatSigned(seven)}</div></div></div><div className="mt-2 text-right text-[9px] text-neutral-600">Open team →</div></Link>; })}</div>
      <div className="hidden overflow-x-auto rounded-lg border border-neutral-800 bg-neutral-900 md:block"><table className="w-full min-w-[940px] text-sm"><thead><tr className="border-b border-neutral-800 text-[10px] uppercase tracking-wide text-neutral-500"><th className="px-3 py-2 text-left">Rank</th><th className="px-3 py-2 text-left">Team</th><th className="px-2 py-2 text-right">{draftMarketAvailable ? "Total capital" : "Player capital"}</th><th className="px-2 py-2 text-right">Players</th><th className="px-2 py-2 text-right">Picks</th><th className="px-2 py-2 text-right">Optimal lineup</th><th className="px-2 py-2 text-right">Depth</th><th className="px-2 py-2 text-right">7d</th></tr></thead><tbody>{capitalOrder.map((value) => { const seven = comparableChange(value.change7d, value.change7dCoverage, value.playerCount); const capitalValue = draftMarketAvailable ? value.totalDynastyValue : value.playerCapital; return <tr key={value.managerId} className="border-b border-neutral-900 hover:bg-neutral-800/30"><td className="px-3 py-2 text-neutral-500">#{capitalRank.get(value.managerId)}</td><td className="px-3 py-2"><Link href={`/league/${value.managerId}`} className="font-medium text-neutral-100 hover:text-emerald-300">{value.teamName}</Link><div className="text-[9px] text-neutral-600">{value.valuedPlayerCount}/{value.playerCount} fresh{draftMarketAvailable ? ` · ${value.draftPickCount} picks` : " · picks withheld"}{value.stalePlayerCount ? ` · ${value.stalePlayerCount} stale` : ""}</div></td><td className={`px-2 py-2 text-right font-semibold tabular-nums ${value.stalePlayerCount || draftMarketStale ? "text-amber-200" : "text-neutral-100"}`}>{formatPoints(capitalValue)}</td><td className="px-2 py-2 text-right"><div>{formatPoints(value.playerCapital)}</div><div className="text-[9px] text-neutral-600">#{playerRank.get(value.managerId)}</div></td><td className="px-2 py-2 text-right">{draftMarketAvailable ? <><div>{formatPoints(value.draftCapital)}</div><div className="text-[9px] text-neutral-600">#{pickRank.get(value.managerId)}</div></> : <span className="text-neutral-700">—</span>}</td><td className="px-2 py-2 text-right"><div>{formatPoints(value.optimalLineupValue)}</div><div className="text-[9px] text-neutral-600">#{lineupRank.get(value.managerId)}</div></td><td className="px-2 py-2 text-right"><div>{formatPoints(value.depthValue)}</div><div className="text-[9px] text-neutral-600">#{depthRank.get(value.managerId)}</div></td><td className={`px-2 py-2 text-right ${trendColorClass(seven)}`}><div>{formatSigned(seven)}</div><div className="text-[9px] text-neutral-600">{value.change7dCoverage}/{value.playerCount}</div></td></tr>; })}</tbody></table></div>
    </section>
    <section><SectionHeader title="Roster construction"/><div className={`grid grid-cols-1 gap-3 ${draftMarketAvailable ? "sm:grid-cols-3" : "sm:grid-cols-2"}`}>{([["Best optimized lineups", rankedLineup, "optimalLineupValue"], ...(draftMarketAvailable ? [["Most draft capital", rankedPicks, "draftCapital"]] : []), ["Most depth capital", rankedDepth, "depthValue"]] as [string, typeof valuations, "optimalLineupValue" | "draftCapital" | "depthValue"][]).map(([title, list, key]) => <div key={title} className="rounded-lg border border-neutral-800 bg-neutral-900 p-3"><h3 className="text-xs font-semibold text-neutral-200">{title}</h3><ol className="mt-2 space-y-2 text-xs">{list.slice(0, 5).map((value, index) => <li key={value.managerId} className="flex justify-between gap-2"><Link href={`/league/${value.managerId}`} className="truncate text-neutral-300 hover:text-emerald-300">#{index + 1} {value.teamName}</Link><span className="text-neutral-500">{formatPoints(value[key])}</span></li>)}</ol></div>)}</div></section>
    {rangeEligible.length ? <section><SectionHeader title="Decision-grade tracked range" description="Requires at least three valid observations spanning 14+ days."/><div className="grid grid-cols-1 gap-3 lg:grid-cols-2"><div className="rounded-lg border border-neutral-800 bg-neutral-900 p-3"><h3 className="mb-2 text-xs font-semibold text-neutral-200">Closest to tracked high</h3><ol className="space-y-1.5">{nearHigh.map(({ entry, market }, index) => <li key={entry.playerId} className="grid grid-cols-[20px_1fr_auto] items-center gap-2 rounded-md bg-neutral-950 px-2.5 py-2 text-xs"><span className="text-neutral-600">{index + 1}</span><Link href={`/players/${entry.playerId}`} className="truncate text-neutral-100 hover:text-emerald-300">{entry.player.fullName}</Link><span className="text-neutral-300">{formatPercent(market.distanceFromHigh?.percent)}</span></li>)}</ol></div><div className="rounded-lg border border-neutral-800 bg-neutral-900 p-3"><h3 className="mb-2 text-xs font-semibold text-neutral-200">Largest drawdowns</h3><ol className="space-y-1.5">{drawdowns.map(({ entry, market }, index) => <li key={entry.playerId} className="grid grid-cols-[20px_1fr_auto] items-center gap-2 rounded-md bg-neutral-950 px-2.5 py-2 text-xs"><span className="text-neutral-600">{index + 1}</span><Link href={`/players/${entry.playerId}`} className="truncate text-neutral-100 hover:text-emerald-300">{entry.player.fullName}</Link><span className="text-red-300">{formatPercent(market.distanceFromHigh?.percent)}</span></li>)}</ol></div></div></section> : null}
  </div>;
}
