import Link from "next/link";
import { getFullAudit } from "@/lib/fullAudit";
import { formatDateTimeEastern } from "@/lib/format";

export const dynamic = "force-dynamic";

const FEATURED = ["current_brett_players", "future_picks", "audit_core_per_league", "history_best_trades", "history_worst_trades", "recommendations", "playbook_bois_best", "playbook_bois_worst", "trends_manager_season"];

function NativeTable({ table }: { table: { name: string; description: string; rows: Array<Record<string, unknown>> } }) {
  const columns = [...new Set(table.rows.flatMap(row => Object.keys(row)))].slice(0, 14);
  const visible = table.rows.slice(0, 80);
  return <section className="overflow-hidden rounded-lg border border-neutral-800 bg-neutral-900"><div className="flex flex-wrap items-start justify-between gap-2 border-b border-neutral-800 px-4 py-3"><div><h2 className="text-base font-semibold text-neutral-100">{table.name.replaceAll("_", " ")}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-neutral-500">{table.description || `${table.rows.length.toLocaleString()} rows from the current full audit.`}</p></div><Link href={`/audit/research?table=${encodeURIComponent(table.name)}`} className="rounded border border-neutral-700 px-2 py-1 text-[11px] text-neutral-300">Open table</Link></div><div className="max-w-full overflow-auto"><table className="w-full min-w-[720px] text-xs"><thead className="bg-neutral-950"><tr>{columns.map(column => <th key={column} className="whitespace-nowrap border-b border-neutral-800 px-3 py-2 text-left font-medium text-neutral-500">{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{visible.map((row, index) => <tr key={index} className="border-b border-neutral-800/80 last:border-0">{columns.map(column => <td key={column} className="max-w-sm px-3 py-2 align-top text-neutral-300">{row[column] === null || row[column] === undefined || row[column] === "" ? "—" : typeof row[column] === "object" ? JSON.stringify(row[column]) : String(row[column])}</td>)}</tr>)}</tbody></table></div>{table.rows.length > visible.length && <div className="border-t border-neutral-800 px-4 py-2 text-xs text-neutral-500">Showing the first {visible.length} of {table.rows.length.toLocaleString()} rows. Open the table for search and pagination.</div>}</section>;
}

export default async function AuditReportPage({ searchParams }: { searchParams: Promise<{ table?: string }> }) {
  const query = await searchParams;
  const audit = await getFullAudit();
  const selected = query.table ? audit.data.tables.find(table => table.name === query.table) : null;
  const featured = FEATURED.map(name => audit.data.tables.find(table => table.name === name)).filter((table): table is NonNullable<typeof table> => !!table);
  const pdfUrl = `/api/audit/research?${new URLSearchParams({ run: audit.id, file: "Dynasty-Bois-Report.pdf" })}`;
  const workbookUrl = `/api/audit/research?${new URLSearchParams({ run: audit.id, file: "Dynasty-Bois-Data.xlsx" })}`;
  return <main className="min-w-0 space-y-6"><section className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/audit" className="text-xs text-emerald-400">← Live audit overview</Link><h1 className="mt-2 text-2xl font-semibold text-neutral-100">Full Dynasty Bois Report</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">A native, live report for Orlando Oswalds and the league. It renders the validated full-audit data directly in the dashboard; the same source bundle powers the Excel and PDF downloads.</p><p className="mt-2 text-xs text-neutral-500">Generated {formatDateTimeEastern(audit.data.generatedAt)} · {audit.data.tables.length} research tables · refreshed by the validated 8 a.m. ET research pass.</p></div><div className="flex gap-2"><Link href="/audit/research" className="rounded border border-neutral-700 px-3 py-2 text-sm text-neutral-200">Browse all tables</Link><a href={workbookUrl} className="rounded border border-neutral-700 px-3 py-2 text-sm text-neutral-200">Download Excel</a><a href={pdfUrl} className="rounded border border-emerald-800 px-3 py-2 text-sm text-emerald-300">Download PDF</a></div></section><section className="rounded-lg border border-emerald-900/60 bg-emerald-950/15 p-4"><h2 className="text-sm font-semibold text-emerald-200">Report contents</h2><p className="mt-1 text-xs leading-5 text-neutral-400">The sections below are the report’s live roster, league, history, trading, recommendation and trend tables. Every remaining workbook table is available from the table index without leaving the dashboard.</p><div className="mt-3 flex flex-wrap gap-2">{audit.data.tables.map(table => <Link key={table.name} href={`/audit/report?table=${encodeURIComponent(table.name)}`} className={`rounded border px-2 py-1 text-[10px] ${selected?.name === table.name ? "border-emerald-600 bg-emerald-950/50 text-emerald-200" : "border-neutral-700 text-neutral-400 hover:text-neutral-100"}`}>{table.name.replaceAll("_", " ")}</Link>)}</div></section>{selected ? <NativeTable table={selected} /> : featured.map(table => <NativeTable key={table.name} table={table} />)}</main>;
}
