const fs=require('fs');const path=require('path');const root=process.cwd();
const R=(p)=>fs.readFileSync(path.join(root,p),'utf8');const W=(p,s)=>fs.writeFileSync(path.join(root,p),s);
function sub(p,a,b,label,optional=false){let s=R(p);if(s.includes(b)){console.log('already',label);return;}if(!s.includes(a)){if(optional){console.log('optional missing',label);return;}throw new Error(`missing ${label}`)}W(p,s.replace(a,b));console.log('applied',label)}
function rx(p,re,b,label,optional=false){let s=R(p);if(!re.test(s)){if(optional){console.log('optional missing',label);return;}throw new Error(`missing ${label}`)}W(p,s.replace(re,b));console.log('applied',label)}

sub('src/lib/refresh.ts',`    const valuedIds = new Set((valued as { playerId: string }[]).map((v) => v.playerId));\n    mappingWarnings = remaining.filter((p) => !valuedIds.has(p.id)).map((p) => ({\n      sleeperId: p.sleeperId,\n      name: \`${'${p.fullName}'} (${'${p.position}'})\`,\n      reason: \`Identified via Sleeper ID ${'${p.sleeperId}'}; no current KTC/Tradyr/Dynasty Dealer market value was found in this refresh.\`,\n    }));`,`    const valuedIds = new Set((valued as { playerId: string }[]).map((v) => v.playerId));\n    for (const p of remaining) {\n      await prisma.player.update({ where: { id: p.id }, data: {\n        mappingStatus: "MAPPED",\n        mappingNote: valuedIds.has(p.id)\n          ? "Sleeper identity verified; fresh trusted-market match resolved by provider ID/name+position."\n          : "Sleeper identity verified; player is identified even though no current trusted market price is available.",\n      }});\n    }\n    mappingWarnings = remaining.filter((p) => !valuedIds.has(p.id)).map((p) => ({\n      sleeperId: p.sleeperId,\n      name: \`${'${p.fullName}'} (${'${p.position}'})\`,\n      reason: \`Identified via Sleeper ID ${'${p.sleeperId}'}; valuation gap only — no current KTC/Tradyr/Dynasty Dealer price was found in this refresh.\`,\n    }));`,'future identity resolution');

sub('src/lib/marketSources.ts','export type MarketSourceKey = "KTC" | "STATSGUY" | "DYNASTYDEALER";','export type MarketSourceKey = "KTC" | "STATSGUY" | "DYNASTYDEALER" | "TRADYR";','market status key Tradyr');
sub('src/lib/marketSources.ts','statsGuyValue:number|null; statsGuyRawValue:number|null; dynastyDealerValue:number|null; dynastyDealerRawValue:number|null;','statsGuyValue:number|null; statsGuyRawValue:number|null; dynastyDealerValue:number|null; dynastyDealerRawValue:number|null; tradyrValue:number|null; tradyrRawValue:number|null;','market mix Tradyr fields');
sub('src/lib/marketSources.ts','statsGuyValue:null,statsGuyRawValue:null,dynastyDealerValue:null,dynastyDealerRawValue:null});','statsGuyValue:null,statsGuyRawValue:null,dynastyDealerValue:null,dynastyDealerRawValue:null,tradyrValue:null,tradyrRawValue:null});','market mix Tradyr init');
sub('src/lib/marketSources.ts','if(!["KTC","STATSGUY","DYNASTYDEALER"].includes(m.source))continue;','if(!["KTC","STATSGUY","DYNASTYDEALER","TRADYR"].includes(m.source))continue;','market mix reads Tradyr');
sub('src/lib/marketSources.ts','if(m.source==="DYNASTYDEALER"){row.dynastyDealerRawValue=m.rawValue;if(meta.scale==="KTC_EQUIVALENT")row.dynastyDealerValue=m.normalizedValue;}','if(m.source==="DYNASTYDEALER"){row.dynastyDealerRawValue=m.rawValue;if(meta.scale==="KTC_EQUIVALENT"&&meta.calibrationExtrapolated!==true)row.dynastyDealerValue=m.normalizedValue;}if(m.source==="TRADYR"){row.tradyrRawValue=m.rawValue;if(meta.scale==="KTC_EQUIVALENT"&&meta.calibrationExtrapolated!==true)row.tradyrValue=m.normalizedValue;}','market mix extracts trusted secondaries');
sub('src/lib/marketSources.ts','for(const source of ["KTC","STATSGUY","DYNASTYDEALER"] as MarketSourceKey[])','for(const source of ["KTC","TRADYR","DYNASTYDEALER","STATSGUY"] as MarketSourceKey[])','source status includes Tradyr');

sub('src/app/(app)/page.tsx','<div className="shrink-0 text-right text-emerald-400"><div className="text-sm font-semibold">{formatSigned(window.riser.points)}</div><div className="text-[9px]">{window.riser.percent >= 0 ? "+" : ""}{window.riser.percent.toFixed(1)}%</div></div>','<div className="shrink-0 text-right text-emerald-400"><div className="text-base font-semibold">{window.riser.percent >= 0 ? "+" : ""}{window.riser.percent.toFixed(1)}%</div><div className="text-[9px] text-emerald-500/80">{formatSigned(window.riser.points)} · from {formatPoints(window.riser.fromValue)}</div></div>','home riser percent first');
sub('src/app/(app)/page.tsx','<div className="shrink-0 text-right text-red-400"><div className="text-sm font-semibold">{formatSigned(window.faller.points)}</div><div className="text-[9px]">{window.faller.percent >= 0 ? "+" : ""}{window.faller.percent.toFixed(1)}%</div></div>','<div className="shrink-0 text-right text-red-400"><div className="text-base font-semibold">{window.faller.percent >= 0 ? "+" : ""}{window.faller.percent.toFixed(1)}%</div><div className="text-[9px] text-red-500/80">{formatSigned(window.faller.points)} · from {formatPoints(window.faller.fromValue)}</div></div>','home faller percent first');

sub('src/app/(app)/league/page.tsx','const candidates=[{source:"Stats Guy",value:mix?.statsGuyValue??null},{source:"Dynasty Dealer",value:mix?.dynastyDealerValue??null}]','const candidates=[{source:"Tradyr",value:mix?.tradyrValue??null},{source:"Dynasty Dealer",value:mix?.dynastyDealerValue??null}]','league trusted source disagreement');
sub('src/app/(app)/league/page.tsx','Stats Guy is translated onto the KTC scale first.','Tradyr and Dynasty Dealer are independently translated onto the KTC scale first.','league source wording',true);

rx('src/app/(app)/settings/page.tsx',/import \{ KTC_DIRECT_REFRESH_ENABLED, KTC_FORMAT_LABEL, MARKET_SOURCE_MAX_AGE_HOURS, SLEEPER_LEAGUE_ID, ORLANDO_OSWALDS_SLEEPER_USER_ID, STATSGUY_REFRESH_ENABLED, DYNASTYDEALER_REFRESH_ENABLED, DISPLAY_TIMEZONE \} from "@\/lib\/config";/,'import { KTC_DIRECT_REFRESH_ENABLED, KTC_FORMAT_LABEL, MARKET_SOURCE_MAX_AGE_HOURS, SLEEPER_LEAGUE_ID, ORLANDO_OSWALDS_SLEEPER_USER_ID, DYNASTYDEALER_REFRESH_ENABLED, TRADYR_REFRESH_ENABLED, DISPLAY_TIMEZONE } from "@/lib/config";','settings imports');
sub('src/app/(app)/settings/page.tsx','    { key:"STATSGUY" as const, enabled:STATSGUY_REFRESH_ENABLED, label:"Stats Guy Fantasy", detail:"Independent daily market source · official API · translated onto KTC scale only from same-refresh overlap" },\n    { key:"DYNASTYDEALER" as const, enabled:DYNASTYDEALER_REFRESH_ENABLED, label:"Dynasty Dealer", detail:"Independent real-Sleeper-trade market · public API · translated onto KTC scale and reliability-gated per player" },','    { key:"TRADYR" as const, enabled:TRADYR_REFRESH_ENABLED, label:"Tradyr", detail:"Verified public dynasty API · freshness-gated · translated onto KTC scale and trust-gated per player" },\n    { key:"DYNASTYDEALER" as const, enabled:DYNASTYDEALER_REFRESH_ENABLED, label:"Dynasty Dealer", detail:"Independent real-Sleeper-trade market · public API · translated onto KTC scale and reliability-gated per player" },','settings Tradyr source');
sub('src/app/(app)/settings/page.tsx','Build: PATCH 13 · preserves PATCH 11 UX + PATCH 12 recovery','Build: PATCH 14 · PATCH 11 UX + PATCH 12 recovery + Tradyr + persistent NFL game intelligence','settings Patch14 marker');
sub('src/app/(app)/settings/page.tsx','KTC is the 70% anchor. Stats Guy and Dynasty Dealer each start at 15% after same-refresh position-aware calibration onto the KTC scale. A secondary is downweighted or excluded per player when the calibration is extrapolated or it remains implausibly far from live KTC; raw source numbers are never averaged directly with KTC.','KTC is the canonical anchor. Tradyr and Dynasty Dealer are independently translated onto the KTC scale and participate only when fresh, non-extrapolated, and inside the trust band. Stats Guy is historical diagnostic data only and does not affect consensus or signals.','settings consensus source policy');
sub('src/app/(app)/settings/page.tsx','It retains the latest copy plus 30 daily recovery points.','It retains the latest copy, an immutable full snapshot for every refresh (up to 250), and 90 daily recovery points.','settings backup retention');
sub('src/app/(app)/settings/page.tsx','Currently-rostered players with no confirmed KTC mapping. Direct Sleeper-ID sources can still value them; KTC name matching stays flagged rather than silently dropping a player.','Every rostered asset is identified by Sleeper ID. This section represents valuation gaps only; a missing market price never turns a known Sleeper player into an “unmapped player.”','settings mapping explanation');

sub('src/components/RefreshButton.tsx','requestedSources:["sleeper","ktc","statsguy","consensus","nflverse-context"]','requestedSources:["sleeper","ktc","tradyr","dynastydealer","consensus","nflverse-player-history","game-grades","secondary-backup"]','refresh pending-source view');
sub('src/components/RefreshButton.tsx','Sync Sleeper, KTC, Stats Guy Fantasy, and NFL context, then rebuild the verified-source consensus.','Sync Sleeper, KTC, Tradyr, Dynasty Dealer, historical/current NFL stats and game grades, then save an independent recovery snapshot.','refresh button copy');

console.log('PATCH 14 RUNTIME COMPLETE');
