import Link from "next/link";
import type { getFullAudit } from "@/lib/fullAudit";
import { formatDateTimeEastern } from "@/lib/format";

const SECTIONS = [
  { title: "League snapshot", description: "The current league-wide roster, value, and draft-pick picture.", tables: ["audit_core_per_league", "current_brett_players", "future_picks"] },
  { title: "Orlando Oswald trade review", description: "Your strongest and weakest historical Dynasty Bois trades, with present-day outcomes.", tables: ["playbook_bois_best", "playbook_bois_worst", "history_best_trades", "history_worst_trades"] },
  { title: "Strategy and recommendations", description: "Decision research and descriptive findings drawn from the complete trade history.", tables: ["recommendations", "playbook_bois_month", "playbook_bois_phase", "playbook_formula_bois"] },
  { title: "League history and trends", description: "Manager history, activity, results, and long-term league patterns.", tables: ["trends_manager_season", "history_activity_by_league", "history_trade_mgr_rank", "history_partners"] },
] as const;

const TABLE_TITLES: Record<string, string> = { current_brett_players: "Orlando Oswald roster", future_picks: "Future rookie picks", audit_core_per_league: "League overview", playbook_bois_best: "Best Dynasty Bois trades", playbook_bois_worst: "Costliest Dynasty Bois trades", history_best_trades: "Best trades in league history", history_worst_trades: "Costliest trades in league history", recommendations: "Strategy recommendations", trends_manager_season: "Manager season trends", history_activity_by_league: "League activity by season", history_trade_mgr_rank: "Manager trade rankings", history_partners: "Trade partners", playbook_bois_month: "Trade outcomes by month", playbook_bois_phase: "Trade outcomes by career phase", playbook_formula_bois: "Trade-pattern model", ledger_brett_partners: "Orlando Oswald trade partners", ledger_brett_rank_by_league: "Orlando Oswald standing by season", brett_trades_ranked: "Orlando Oswald trades ranked", playbook_brett_best: "Orlando Oswald best trades", playbook_brett_worst: "Orlando Oswald costliest trades" };

function displayText(value: unknown) { return String(value).replaceAll(/BrettTulip/gi, "Orlando Oswald").replaceAll(/Brett's/gi, "Orlando Oswald's").replaceAll(/\bBrett\b/gi, "Orlando Oswald").replaceAll(/jeffsharpington/gi, "Jeff"); }
function tableTitle(name: string) { return TABLE_TITLES[name] ?? displayText(name.replaceAll("_", " ")).replace(/\b\w/g, letter => letter.toUpperCase()); }
type AuditTable = Awaited<ReturnType<typeof getFullAudit>>["data"]["tables"][number];

function NativeTable({ table, expanded = false }: { table: AuditTable; expanded?: boolean }) {
  const columns = [...new Set(table.rows.flatMap((row) => Object.keys(row)))].slice(0, 14), visible = table.rows.slice(0, expanded ? 100 : 20);
  return <section className="overflow-hidden rounded-lg border border-neutral-800 bg-neutral-900"><div className="flex flex-wrap items-start justify-between gap-2 border-b border-neutral-800 px-4 py-3"><div><h2 className="text-base font-semibold text-neutral-100">{tableTitle(table.name)}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-neutral-500">{displayText(table.description || `${table.rows.length.toLocaleString()} rows from the validated audit.`)}</p></div><Link href={`/audit/research?table=${encodeURIComponent(table.name)}`} className="rounded border border-neutral-700 px-2 py-1 text-[11px] text-neutral-300">Search full table</Link></div><div className="max-w-full overflow-auto"><table className="w-full min-w-[720px] text-xs"><thead className="bg-neutral-950"><tr>{columns.map((column) => <th key={column} className="whitespace-nowrap border-b border-neutral-800 px-3 py-2 text-left font-medium text-neutral-500">{displayText(column.replaceAll("_", " "))}</th>)}</tr></thead><tbody>{visible.map((row, index) => <tr key={index} className="border-b border-neutral-800/80 last:border-0">{columns.map((column) => <td key={column} className="max-w-sm px-3 py-2 align-top text-neutral-300">{row[column] === null || row[column] === undefined || row[column] === "" ? "—" : displayText(typeof row[column] === "object" ? JSON.stringify(row[column]) : row[column])}</td>)}</tr>)}</tbody></table></div>{table.rows.length > visible.length && <div className="border-t border-neutral-800 px-4 py-2 text-xs text-neutral-500">Showing {visible.length} of {table.rows.length.toLocaleString()} rows. Use “Search full table” for the complete dataset.</div>}</section>;
}

export default function FullAuditReport({ audit, selectedName }: { audit: Awaited<ReturnType<typeof getFullAudit>>; selectedName?: string }) {
  const selected = selectedName ? audit.data.tables.find((table) => table.name === selectedName) : null;
  const sections = SECTIONS.map((section) => ({ ...section, tables: section.tables.map((name) => audit.data.tables.find((table) => table.name === name)).filter((table): table is AuditTable => Boolean(table)) })).filter((section) => section.tables.length);
  const grouped = new Set(sections.flatMap((section) => section.tables.map((table) => table.name))), referenceTables = audit.data.tables.filter((table) => !grouped.has(table.name));
  const downloadQuery = (file: string) => `/api/audit/research?${new URLSearchParams({ run: audit.id, file })}`;
  return <main className="min-w-0 space-y-7"><section className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/audit" className="text-xs text-emerald-400">← Live audit overview</Link><h1 className="mt-2 text-2xl font-semibold text-neutral-100">Dynasty Bois Report</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-400">A structured, live report of the validated Dynasty Bois audit. It follows the report’s league snapshot, Orlando review, strategy, and history sections; downloads use this same audit run.</p><p className="mt-2 text-xs text-neutral-500">Generated {formatDateTimeEastern(audit.data.generatedAt)} · {audit.data.tables.length} audit tables · refreshed by the validated 8 a.m. ET research pass.</p></div><div className="flex flex-wrap gap-2"><Link href="/audit/research" className="rounded border border-neutral-700 px-3 py-2 text-sm text-neutral-200">All source tables</Link><a href={downloadQuery("Dynasty-Bois-Data.xlsx")} className="rounded border border-neutral-700 px-3 py-2 text-sm text-neutral-200">Download Excel</a><a href={downloadQuery("Dynasty-Bois-Report.pdf")} className="rounded border border-emerald-800 px-3 py-2 text-sm text-emerald-300">Download PDF</a></div></section>{selected ? <NativeTable table={selected} expanded /> : <>{sections.map((section) => <section key={section.title} className="space-y-3"><div className="border-b border-neutral-800 pb-2"><h2 className="text-lg font-semibold text-neutral-100">{section.title}</h2><p className="mt-1 text-xs text-neutral-500">{section.description}</p></div><div className="space-y-3">{section.tables.map((table) => <NativeTable key={table.name} table={table} />)}</div></section>)}<section className="rounded-lg border border-neutral-800 bg-neutral-900 p-4"><h2 className="text-sm font-semibold text-neutral-100">Reference tables</h2><p className="mt-1 text-xs leading-5 text-neutral-500">The remaining {referenceTables.length} audit tables are retained in the complete dataset. Open any one directly when you need a deeper cut without crowding the main report.</p><div className="mt-3 flex flex-wrap gap-2">{referenceTables.map((table) => <Link key={table.name} href={`/audit/report?table=${encodeURIComponent(table.name)}`} className="rounded border border-neutral-700 px-2 py-1 text-[10px] text-neutral-400 hover:text-neutral-100">{tableTitle(table.name)}</Link>)}</div></section></>}</main>;
}
