"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { WaiverMarketRow } from "@/lib/waiverMarket";

const points = (value: number | null) => value == null ? "—" : value.toFixed(1);
const signed = (value: number | null) => value == null ? "—" : `${value > 0 ? "+" : value < 0 ? "" : "±"}${Math.round(value).toLocaleString("en-US")}`;

export default function WaiverMarketBoard({ rows }: { rows: WaiverMarketRow[] }) {
  const [query, setQuery] = useState("");
  const [position, setPosition] = useState("ALL");
  const [sort, setSort] = useState<"value" | "projection" | "move">("value");
  const filtered = useMemo(() => rows.filter((row) => (position === "ALL" || row.position === position) && `${row.fullName} ${row.nflTeam ?? ""}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => sort === "projection" ? (b.projectedPoints ?? -Infinity) - (a.projectedPoints ?? -Infinity) : sort === "move" ? (b.latestMove ?? -Infinity) - (a.latestMove ?? -Infinity) : b.currentValue - a.currentValue), [rows, position, query, sort]);
  return <div className="space-y-3">
    <div className="grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input aria-label="Search unrostered players" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search unrostered player…" className="h-9 rounded-md border border-neutral-800 bg-neutral-900 px-3 text-xs text-neutral-200"/><div className="flex rounded-md border border-neutral-800 bg-neutral-900 p-1">{["ALL", "QB", "RB", "WR", "TE"].map((value) => <button key={value} aria-pressed={position === value} onClick={() => setPosition(value)} className={`rounded px-2.5 py-1 text-xs ${position === value ? "bg-neutral-700 text-white" : "text-neutral-400"}`}>{value}</button>)}</div><select aria-label="Sort waiver players" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} className="h-9 rounded-md border border-neutral-800 bg-neutral-900 px-2 text-xs"><option value="value">Highest KTC</option><option value="projection">Highest weekly projection</option><option value="move">Latest risers</option></select></div>
    <div className="space-y-2 md:hidden">{filtered.map((row) => <Link key={row.id} href={`/players/${row.id}`} className="block rounded-lg border border-neutral-800 bg-neutral-900 p-3"><div className="flex justify-between"><div><div className="font-medium">{row.fullName}</div><div className="text-xs text-neutral-400">{row.position}{row.nflTeam ? ` · ${row.nflTeam}` : ""} · {row.projectedRole}</div></div><div className="text-right"><div className="font-semibold text-emerald-300">{points(row.projectedPoints)} FP</div><div className="text-xs text-neutral-400">KTC {Math.round(row.currentValue)}</div></div></div><div className="mt-2 text-xs text-sky-300">{row.need} · latest {signed(row.latestMove)}</div></Link>)}</div>
    <div className="hidden overflow-x-auto rounded-lg border border-neutral-800 bg-neutral-900 md:block"><table className="w-full min-w-[900px] text-xs"><thead><tr className="border-b border-neutral-800 text-xs uppercase text-neutral-400"><th className="px-3 py-2 text-left">Player</th><th className="px-2 py-2 text-left">Role</th><th className="px-2 py-2 text-left">Your need</th><th className="px-2 py-2 text-right">Week projection</th><th className="px-2 py-2 text-right">KTC</th><th className="px-2 py-2 text-right">Latest move</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-b border-neutral-800"><td className="px-3 py-2"><Link href={`/players/${row.id}`} className="font-medium text-neutral-100 hover:text-emerald-300">{row.fullName}</Link><div className="text-xs text-neutral-400">{row.position}{row.nflTeam ? ` · ${row.nflTeam}` : ""}</div></td><td className="px-2 py-2 text-neutral-300">{row.projectedRole}</td><td className="px-2 py-2 text-sky-300">{row.need}</td><td className="px-2 py-2 text-right font-semibold text-emerald-300">{points(row.projectedPoints)}</td><td className="px-2 py-2 text-right">{Math.round(row.currentValue).toLocaleString()}</td><td className="px-2 py-2 text-right">{signed(row.latestMove)}</td></tr>)}</tbody></table></div>
    {!filtered.length ? <div className="rounded-lg border border-neutral-800 p-6 text-center text-xs text-neutral-400">No unrostered players match these filters.</div> : null}
  </div>;
}
